"""Initial migration

Revision ID: 4564e9c9c31f
Revises: 
Create Date: 2024-01-28 17:58:05.754155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4564e9c9c31f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_diary')
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotionimage_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('pw',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('pw',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('emotionimage_path')

    op.create_table('_alembic_tmp_diary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), sa.ForeignKey('user.id', name='fk_diary_user_id'),nullable=True),
    sa.Column('date', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('emotiontext', sa.VARCHAR(length=20), nullable=True),
    sa.Column('music', sa.TEXT(), nullable=True),
    sa.Column('emotionimage_path', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
